ClusterName=gpu_cluster
ControlMachine=controller
ControlAddr=192.168.1.10
SlurmUser=slurm
AuthType=auth/munge
StateSaveLocation=/cluster/slurm/state
SlurmdSpoolDir=/var/spool/slurmd
ProctrackType=proctrack/linuxproc
TaskPlugin=task/cgroup
JobAcctGatherType=jobacct_gather/none
SelectType=select/cons_tres
SelectTypeParameters=CR_Core_Memory
ReturnToService=1
GresTypes=gpu

# --- NODES ---
NodeName=node01 NodeAddr=192.168.1.73 CPUs=12 Boards=1 SocketsPerBoard=1 CoresPerSocket=6 ThreadsPerCore=2 RealMemory=15000 Gres=gpu:1
NodeName=node02 NodeAddr=192.168.1.74 CPUs=12 Boards=1 SocketsPerBoard=1 CoresPerSocket=6 ThreadsPerCore=2 RealMemory=31000 Gres=gpu:1

# --- PARTITION ---
PartitionName=gpu_part Nodes=node[01-02] Default=YES MaxTime=INFINITE State=UP
DebugFlags=NO_CONF_HASH

# --- Power Management Automation (Optimized) ---
SuspendProgram=/cluster/slurm/scripts/suspend.sh
ResumeProgram=/cluster/slurm/scripts/resume.sh

# 10 minute (600 seconds) tak idle rehne par hi node off hogi
SuspendTime=36000

# Boot-up ke liye 5 minute (300s) kafi hain
ResumeTimeout=300

# Shutdown hone ke liye 5 minute (300s)
SuspendTimeout=300

# Job shuru hone ka intezar (Slow boot ke liye behtar hai)
BatchStartTimeout=120

# Unlimited rate (0) taake sab nodes ek saath jag saken
ResumeRate=0
SuspendRate=0
